USE [master]
GO

/****** Object:  Database [HospitalDB]    Script Date: 27-10-2022 12:36:21 ******/
CREATE DATABASE [HospitalDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HospitalDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HospitalDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HospitalDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HospitalDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HospitalDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HospitalDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HospitalDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HospitalDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HospitalDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HospitalDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HospitalDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HospitalDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HospitalDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HospitalDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HospitalDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HospitalDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HospitalDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HospitalDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HospitalDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HospitalDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HospitalDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HospitalDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HospitalDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HospitalDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HospitalDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HospitalDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HospitalDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HospitalDB] SET RECOVERY FULL 
GO

ALTER DATABASE [HospitalDB] SET  MULTI_USER 
GO

ALTER DATABASE [HospitalDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HospitalDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HospitalDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HospitalDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HospitalDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HospitalDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HospitalDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HospitalDB] SET  READ_WRITE 
GO

